import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarTrigger } from "@/components/ui/sidebar";

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const SIDEBAR_WIDTH = 260; // px

export default function RootLayout({ children }) {
	return (
		<html lang="pt-br">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<SidebarProvider>
					<div className="flex min-h-screen min-w-screen">
						<div className="relative">
							<AppSidebar />
							<SidebarTrigger className="absolute right-0 top-4 z-50 h-6 w-6 rounded-full border bg-white shadow-md translate-x-1/2" />
						</div>
						<main className="flex-1" style={{ minWidth: 0 }}>
							{children}
						</main>
					</div>
				</SidebarProvider>
			</body>
		</html>
	);
}
